### ISSUE TITLE
Indicate which version of Java Parquet this is a port of

### ISSUE THREAD

**Issue by drauschenbach** [ironSource/parquetjs#27]
The README contains links to the HEAD of the github.com/apache/parquet project. I can't figure out which version of Parquet this is a port of.

**Comment by asmuth** [comment]
We're aiming to be compatible with the latest version; testing is currently performed using `parquet-tools-1.9.1`. We did also implement the "v1" file formats though, so it should also be compatible with older versions (this has not been thoroughly tested though).
