### ISSUE TITLE
get file content as base64

### ISSUE THREAD

**Issue by LiranBri** [ironSource/parquetjs#28]
Hi,
is there a way to get the parquet file as base64 string, without having to write it to disk?

my use case is to convert an object into parquet format and upload it to AWS s3

**Comment by LiranBri** [comment]
looks like there is a [pending PR](https://github.com/ironSource/parquetjs/pull/26) that would allow me to do it (and for the same use case)
would appreciate if you can merge

**Comment by asmuth** [comment]
#26 has been merged
