### ISSUE TITLE
Does parquetjs run under VS2017/node_v8.11.4 ?

### ISSUE THREAD

**Issue by christian2345** [ironSource/parquetjs#71]
Hi there,

I have installed - with some difficulty - parquetjs under node v8.11.4 in win10/VisualStudio2017. The ultimate destination is a Lambda function under AWS. However, there are some errors during the load phase (fs.opensync(config.json) - which does not exist at the path provided). I am wondering if parquetjs can be used in this environment ... ?

[parquetjs_install.txt](https://github.com/ironSource/parquetjs/files/2299547/parquetjs_install.txt)

**Comment by ZJONSSON** [comment]
Parquetjs works well on AWS Lambda.  However since lambda runs on linux you might have to build parquetjs (which include thrift c++ modules that have to be compiled) in a linux docker or vm.

**Comment by vweevers** [comment]
If you go with Docker: [`amazonlinux:2017.03`](https://hub.docker.com/r/library/amazonlinux/) matches the [Lambda execution environment](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).

**Comment by christian2345** [comment]
thanks, I'll give it a try - may have to reconsider since win10 is only the development platform for an AWS application

**Comment by ZJONSSON** [comment]
Thanks @vweevers yes this is how I build stuff that has to be compiled.   @christian2345  Visual Studio (Windows) has plugin to publish to aws lambda, but that is not the only delivery mechanism.   You can go directly to aws lambda and upload a zip file or use the aws-cli:
```
aws lambda update-function-code --function-name my-function --zip-file fileb://mycode.zip
```

**Comment by aconanlai** [comment]
@ZJONSSON Are there any additional steps you have to take in order to make it work on Lambda? I have a Docker container running amazon linux with node 8.10, running `npm install` on my project which includes `parquetjs`. After zipping and uploading, my Lambda still gives me an error like before:
`"errorMessage": "/var/lang/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/node_modules/lzo/build/Release/node_lzo.node)",`

Is there anything I have to do like moving `.so` files to a `/lib` folder?

**Comment by vweevers** [comment]
@aconanlai Amazon Linux 1 or Amazon Linux 2? You may need to install or update some packages in order to build native modules:

```
sudo yum install gcc gcc-c++ libgcc make
```

**Comment by vweevers** [comment]
Sorry, I misread, didn't see you already successfully ran `npm install`.

**Comment by aconanlai** [comment]
@vweevers thanks for the response. this is what i'm doing:

```
FROM amazonlinux:latest

add my files, etc

RUN yum install gcc44 gcc-c++ libgcc44 cmake wget tar zip gzip make -y

install node, etc

npm install

zip, upload, etc
```

**Comment by anton-yurchenko** [comment]
@aconanlai, are you copying **node_modules** to docker image? Try adding **node_modules** to **.dockerignore** file?

**Comment by aconanlai** [comment]
@anton-yurchenko i'm only copying my lambda code and the `package.json`.

**Comment by aconanlai** [comment]
i solved this by using images from here rather than the `amazonlinux` image:

https://github.com/lambci/docker-lambda
