### ISSUE TITLE
All values in stream _transform row are either null or undefined

### ISSUE THREAD

**Issue by ochart2** [ironSource/parquetjs#83]
I return new parquet.ParquetTransformer(schema);

and then I write to the stream as normal... all the values for the document are either null or undefined when inspecting them in ParquetTransformer _transform method.

What is the correct way to use streams with parquetjs?

**Comment by ochart2** [comment]
Got it working. Thanks for the lib!

**Comment by jdhankins** [comment]
@ochart2, could you upload your solution?  Thanks for your help.

**Comment by ochart2** [comment]
Looks something like this:
```ts
import {Transform} from 'stream';
import * as parquet from 'parquetjs';

const types: any = {
	string: { compression: 'GZIP', type: 'UTF8' },
	int: { compression: 'GZIP', type: 'INT32', encoding: 'RLE', bitWidth: 7 },
	date: { compression: 'GZIP', type: 'TIMESTAMP_MILLIS', encoding: 'RLE', bitWidth: 7 },
};

const schema = new parquet.ParquetSchema({
	a: types.string,
	b: types.int,
	c: types.date,
});

export const newParquetStream = function (): Transform {
	return new parquet.ParquetTransformer(schema);
};
```

I was having issues reading the parquet file from Redshift... Good luck, let me know how you fare.
